services:
  - type: web
    name: planka
    env: node
    build:
      dockerfile: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgres://planka0b_user:zz8CEqmhEJo4L63s10UPV08F1M5k8R@dpg-djjtt4d3jp1c78ep1kd9-3.avgapnoodaccess_2gxddec:5432/planka0b
      - key: PGSSLMODE
        value: require
      - key: BASE_URL
        value: https://seu-app.onrender.comservices:
  - type: web
    name: planka
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgres://plankadb_user:zzSCEqmHbEbQeL63ssDUPXM8F1NkEkBR@dpg-djjtr4u3jplc73eplks0-a.oregon-postgres.render.com:5432/plankadb?sslmode=require
      - key: REDIS_URL
        value: redis://default:vTJDH6UoRyByqqJQ3GLZasu0WdkdopgK@redis-15273.c74.us-east-1-4.ec2.redns.redis-cloud.com:15273
      - key: SECRET_KEY
        value: vTJDH6UoRyByqqJQ3GLZasu0WdkdopgK
    branch: main
    autoDeploy: true
